enum AppLanguage { ru, en, az, tr, es, fr, de, ar, zh, pt }

/// Словарь переводов интерфейса на 10 самых распространённых языков.
class AppStrings {
  static const Map<AppLanguage, Map<String, String>> _dict = {
    AppLanguage.ru: {
      'app_title': 'Мои траты',
      'period_week': 'Неделя',
      'period_month': 'Месяц',
      'period_all': 'Всё время',
      'spent': 'ПОТРАЧЕНО',
      'limit_over': 'Лимит превышен',
      'limit_left': 'Осталось',
      'limit_of': 'из',
      'set_limit': 'Задать лимит на месяц',
      'change_limit': 'Изменить лимит',
      'add_expense': 'ДОБАВИТЬ ТРАТУ',
      'history': 'ИСТОРИЯ',
      'search_hint': 'Поиск по категории или комментарию',
      'empty_history': 'Пока пусто — выбери категорию выше, чтобы добавить первую трату.',
      'add_button': 'Добавить',
      'date': 'Дата',
      'comment_optional': 'Комментарий (необязательно)',
      'new_category': 'Новая категория',
      'category_name_hint': 'название категории',
      'icon_label': 'Иконка',
      'color_label': 'Цвет',
      'create_category': 'Создать категорию',
      'monthly_limit_title': 'Лимит на месяц',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'own_category': 'Своя',
      'avg_per_day': 'В среднем в день',
      'top_category': 'Больше всего',
      'error_amount': 'Введи сумму больше нуля',
      'error_category_name': 'Введи название категории',
      'no_top_category': '—',
      'own_category_hint': 'своя категория',
      'cat_food': 'Еда', 'hint_food': 'например: шаурма, кофе, продукты',
      'cat_transport': 'Транспорт', 'hint_transport': 'например: такси, бензин, автобус',
      'cat_fun': 'Развлечения', 'hint_fun': 'например: кино, игра, концерт',
      'cat_clothes': 'Одежда', 'hint_clothes': 'например: кроссовки, куртка',
      'cat_home': 'Жильё', 'hint_home': 'например: аренда, коммуналка',
      'cat_health': 'Здоровье', 'hint_health': 'например: аптека, врач',
      'cat_subs': 'Подписки', 'hint_subs': 'например: музыка, стриминг',
      'cat_beauty': 'Красота', 'hint_beauty': 'например: стрижка, косметика',
      'cat_study': 'Учёба', 'hint_study': 'например: курсы, книги',
      'cat_gifts': 'Подарки', 'hint_gifts': 'например: другу, родным',
      'cat_pets': 'Питомцы', 'hint_pets': 'например: корм, ветеринар',
      'cat_other': 'Прочее', 'hint_other': 'что угодно ещё',
    },
    AppLanguage.en: {
      'app_title': 'My Expenses',
      'period_week': 'Week',
      'period_month': 'Month',
      'period_all': 'All time',
      'spent': 'SPENT',
      'limit_over': 'Limit exceeded',
      'limit_left': 'Left',
      'limit_of': 'of',
      'set_limit': 'Set monthly limit',
      'change_limit': 'Change limit',
      'add_expense': 'ADD EXPENSE',
      'history': 'HISTORY',
      'search_hint': 'Search by category or note',
      'empty_history': 'Nothing yet — pick a category above to add your first expense.',
      'add_button': 'Add',
      'date': 'Date',
      'comment_optional': 'Note (optional)',
      'new_category': 'New category',
      'category_name_hint': 'category name',
      'icon_label': 'Icon',
      'color_label': 'Color',
      'create_category': 'Create category',
      'monthly_limit_title': 'Monthly limit',
      'cancel': 'Cancel',
      'save': 'Save',
      'own_category': 'Custom',
      'avg_per_day': 'Avg. per day',
      'top_category': 'Top category',
      'error_amount': 'Enter an amount greater than zero',
      'error_category_name': 'Enter a category name',
      'no_top_category': '—',
      'own_category_hint': 'custom category',
      'cat_food': 'Food', 'hint_food': 'e.g. shawarma, coffee, groceries',
      'cat_transport': 'Transport', 'hint_transport': 'e.g. taxi, fuel, bus',
      'cat_fun': 'Fun', 'hint_fun': 'e.g. movies, games, concert',
      'cat_clothes': 'Clothes', 'hint_clothes': 'e.g. sneakers, jacket',
      'cat_home': 'Housing', 'hint_home': 'e.g. rent, utilities',
      'cat_health': 'Health', 'hint_health': 'e.g. pharmacy, doctor',
      'cat_subs': 'Subscriptions', 'hint_subs': 'e.g. music, streaming',
      'cat_beauty': 'Beauty', 'hint_beauty': 'e.g. haircut, cosmetics',
      'cat_study': 'Study', 'hint_study': 'e.g. courses, books',
      'cat_gifts': 'Gifts', 'hint_gifts': 'e.g. for a friend, family',
      'cat_pets': 'Pets', 'hint_pets': 'e.g. food, vet',
      'cat_other': 'Other', 'hint_other': 'anything else',
    },
    AppLanguage.az: {
      'app_title': 'Xərclərim',
      'period_week': 'Həftə',
      'period_month': 'Ay',
      'period_all': 'Bütün vaxt',
      'spent': 'XƏRCLƏNİB',
      'limit_over': 'Limit aşılıb',
      'limit_left': 'Qalıb',
      'limit_of': '/',
      'set_limit': 'Aylıq limit təyin et',
      'change_limit': 'Limiti dəyiş',
      'add_expense': 'XƏRC ƏLAVƏ ET',
      'history': 'TARİXÇƏ',
      'search_hint': 'Kateqoriya və ya qeyd üzrə axtar',
      'empty_history': 'Hələ boşdur — ilk xərci əlavə etmək üçün yuxarıdan kateqoriya seç.',
      'add_button': 'Əlavə et',
      'date': 'Tarix',
      'comment_optional': 'Qeyd (məcburi deyil)',
      'new_category': 'Yeni kateqoriya',
      'category_name_hint': 'kateqoriya adı',
      'icon_label': 'İkon',
      'color_label': 'Rəng',
      'create_category': 'Kateqoriya yarat',
      'monthly_limit_title': 'Aylıq limit',
      'cancel': 'Ləğv et',
      'save': 'Yadda saxla',
      'own_category': 'Öz',
      'avg_per_day': 'Gündəlik orta',
      'top_category': 'Ən çox xərclənən',
      'error_amount': 'Sıfırdan böyük məbləğ daxil et',
      'error_category_name': 'Kateqoriya adını daxil et',
      'no_top_category': '—',
      'own_category_hint': 'öz kateqoriyan',
      'cat_food': 'Yemək', 'hint_food': 'məs: şaurma, qəhvə, ərzaq',
      'cat_transport': 'Nəqliyyat', 'hint_transport': 'məs: taksi, benzin, avtobus',
      'cat_fun': 'Əyləncə', 'hint_fun': 'məs: kino, oyun, konsert',
      'cat_clothes': 'Geyim', 'hint_clothes': 'məs: krossovka, gödəkçə',
      'cat_home': 'Ev', 'hint_home': 'məs: kirayə, kommunal',
      'cat_health': 'Sağlamlıq', 'hint_health': 'məs: aptek, həkim',
      'cat_subs': 'Abunəliklər', 'hint_subs': 'məs: musiqi, streaming',
      'cat_beauty': 'Gözəllik', 'hint_beauty': 'məs: bərbərxana, kosmetika',
      'cat_study': 'Təhsil', 'hint_study': 'məs: kurslar, kitablar',
      'cat_gifts': 'Hədiyyələr', 'hint_gifts': 'məs: dosta, ailəyə',
      'cat_pets': 'Ev heyvanları', 'hint_pets': 'məs: yem, baytar',
      'cat_other': 'Digər', 'hint_other': 'nə desən',
    },
    AppLanguage.tr: {
      'app_title': 'Harcamalarım',
      'period_week': 'Hafta',
      'period_month': 'Ay',
      'period_all': 'Tüm zamanlar',
      'spent': 'HARCANAN',
      'limit_over': 'Limit aşıldı',
      'limit_left': 'Kaldı',
      'limit_of': '/',
      'set_limit': 'Aylık limit belirle',
      'change_limit': 'Limiti değiştir',
      'add_expense': 'HARCAMA EKLE',
      'history': 'GEÇMİŞ',
      'search_hint': 'Kategori veya nota göre ara',
      'empty_history': 'Henüz boş — ilk harcamayı eklemek için yukarıdan kategori seç.',
      'add_button': 'Ekle',
      'date': 'Tarih',
      'comment_optional': 'Not (isteğe bağlı)',
      'new_category': 'Yeni kategori',
      'category_name_hint': 'kategori adı',
      'icon_label': 'Simge',
      'color_label': 'Renk',
      'create_category': 'Kategori oluştur',
      'monthly_limit_title': 'Aylık limit',
      'cancel': 'İptal',
      'save': 'Kaydet',
      'own_category': 'Özel',
      'avg_per_day': 'Günlük ortalama',
      'top_category': 'En çok harcanan',
      'error_amount': 'Sıfırdan büyük bir tutar gir',
      'error_category_name': 'Kategori adını gir',
      'no_top_category': '—',
      'own_category_hint': 'özel kategori',
      'cat_food': 'Yemek', 'hint_food': 'örn: dürüm, kahve, market',
      'cat_transport': 'Ulaşım', 'hint_transport': 'örn: taksi, benzin, otobüs',
      'cat_fun': 'Eğlence', 'hint_fun': 'örn: sinema, oyun, konser',
      'cat_clothes': 'Giyim', 'hint_clothes': 'örn: spor ayakkabı, ceket',
      'cat_home': 'Ev', 'hint_home': 'örn: kira, faturalar',
      'cat_health': 'Sağlık', 'hint_health': 'örn: eczane, doktor',
      'cat_subs': 'Abonelikler', 'hint_subs': 'örn: müzik, yayın',
      'cat_beauty': 'Güzellik', 'hint_beauty': 'örn: kuaför, kozmetik',
      'cat_study': 'Eğitim', 'hint_study': 'örn: kurslar, kitaplar',
      'cat_gifts': 'Hediyeler', 'hint_gifts': 'örn: arkadaşa, aileye',
      'cat_pets': 'Evcil hayvanlar', 'hint_pets': 'örn: mama, veteriner',
      'cat_other': 'Diğer', 'hint_other': 'her ne olursa',
    },
    AppLanguage.es: {
      'app_title': 'Mis Gastos',
      'period_week': 'Semana',
      'period_month': 'Mes',
      'period_all': 'Siempre',
      'spent': 'GASTADO',
      'limit_over': 'Límite superado',
      'limit_left': 'Quedan',
      'limit_of': 'de',
      'set_limit': 'Fijar límite mensual',
      'change_limit': 'Cambiar límite',
      'add_expense': 'AÑADIR GASTO',
      'history': 'HISTORIAL',
      'search_hint': 'Buscar por categoría o nota',
      'empty_history': 'Aún vacío — elige una categoría arriba para añadir tu primer gasto.',
      'add_button': 'Añadir',
      'date': 'Fecha',
      'comment_optional': 'Nota (opcional)',
      'new_category': 'Nueva categoría',
      'category_name_hint': 'nombre de la categoría',
      'icon_label': 'Icono',
      'color_label': 'Color',
      'create_category': 'Crear categoría',
      'monthly_limit_title': 'Límite mensual',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'own_category': 'Propia',
      'avg_per_day': 'Promedio diario',
      'top_category': 'Mayor gasto',
      'error_amount': 'Ingresa un monto mayor que cero',
      'error_category_name': 'Ingresa un nombre de categoría',
      'no_top_category': '—',
      'own_category_hint': 'categoría propia',
      'cat_food': 'Comida', 'hint_food': 'ej: shawarma, café, mercado',
      'cat_transport': 'Transporte', 'hint_transport': 'ej: taxi, gasolina, bus',
      'cat_fun': 'Ocio', 'hint_fun': 'ej: cine, juego, concierto',
      'cat_clothes': 'Ropa', 'hint_clothes': 'ej: zapatillas, chaqueta',
      'cat_home': 'Vivienda', 'hint_home': 'ej: alquiler, servicios',
      'cat_health': 'Salud', 'hint_health': 'ej: farmacia, médico',
      'cat_subs': 'Suscripciones', 'hint_subs': 'ej: música, streaming',
      'cat_beauty': 'Belleza', 'hint_beauty': 'ej: peluquería, cosméticos',
      'cat_study': 'Estudios', 'hint_study': 'ej: cursos, libros',
      'cat_gifts': 'Regalos', 'hint_gifts': 'ej: a un amigo, familia',
      'cat_pets': 'Mascotas', 'hint_pets': 'ej: comida, veterinario',
      'cat_other': 'Otros', 'hint_other': 'cualquier otra cosa',
    },
    AppLanguage.fr: {
      'app_title': 'Mes Dépenses',
      'period_week': 'Semaine',
      'period_month': 'Mois',
      'period_all': 'Toujours',
      'spent': 'DÉPENSÉ',
      'limit_over': 'Limite dépassée',
      'limit_left': 'Restant',
      'limit_of': 'sur',
      'set_limit': 'Définir la limite mensuelle',
      'change_limit': 'Changer la limite',
      'add_expense': 'AJOUTER UNE DÉPENSE',
      'history': 'HISTORIQUE',
      'search_hint': 'Rechercher par catégorie ou note',
      'empty_history': 'Encore vide — choisis une catégorie ci-dessus pour ajouter ta première dépense.',
      'add_button': 'Ajouter',
      'date': 'Date',
      'comment_optional': 'Note (facultatif)',
      'new_category': 'Nouvelle catégorie',
      'category_name_hint': 'nom de la catégorie',
      'icon_label': 'Icône',
      'color_label': 'Couleur',
      'create_category': 'Créer la catégorie',
      'monthly_limit_title': 'Limite mensuelle',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'own_category': 'Perso',
      'avg_per_day': 'Moyenne par jour',
      'top_category': 'Plus grosse dépense',
      'error_amount': 'Saisis un montant supérieur à zéro',
      'error_category_name': 'Saisis un nom de catégorie',
      'no_top_category': '—',
      'own_category_hint': 'catégorie personnalisée',
      'cat_food': 'Nourriture', 'hint_food': 'ex : shawarma, café, courses',
      'cat_transport': 'Transport', 'hint_transport': 'ex : taxi, essence, bus',
      'cat_fun': 'Loisirs', 'hint_fun': 'ex : cinéma, jeu, concert',
      'cat_clothes': 'Vêtements', 'hint_clothes': 'ex : baskets, veste',
      'cat_home': 'Logement', 'hint_home': 'ex : loyer, charges',
      'cat_health': 'Santé', 'hint_health': 'ex : pharmacie, médecin',
      'cat_subs': 'Abonnements', 'hint_subs': 'ex : musique, streaming',
      'cat_beauty': 'Beauté', 'hint_beauty': 'ex : coiffeur, cosmétiques',
      'cat_study': 'Études', 'hint_study': 'ex : cours, livres',
      'cat_gifts': 'Cadeaux', 'hint_gifts': 'ex : pour un ami, la famille',
      'cat_pets': 'Animaux', 'hint_pets': 'ex : nourriture, vétérinaire',
      'cat_other': 'Autre', 'hint_other': "n'importe quoi d'autre",
    },
    AppLanguage.de: {
      'app_title': 'Meine Ausgaben',
      'period_week': 'Woche',
      'period_month': 'Monat',
      'period_all': 'Gesamt',
      'spent': 'AUSGEGEBEN',
      'limit_over': 'Limit überschritten',
      'limit_left': 'Übrig',
      'limit_of': 'von',
      'set_limit': 'Monatslimit festlegen',
      'change_limit': 'Limit ändern',
      'add_expense': 'AUSGABE HINZUFÜGEN',
      'history': 'VERLAUF',
      'search_hint': 'Nach Kategorie oder Notiz suchen',
      'empty_history': 'Noch leer — wähle oben eine Kategorie, um deine erste Ausgabe hinzuzufügen.',
      'add_button': 'Hinzufügen',
      'date': 'Datum',
      'comment_optional': 'Notiz (optional)',
      'new_category': 'Neue Kategorie',
      'category_name_hint': 'Kategoriename',
      'icon_label': 'Symbol',
      'color_label': 'Farbe',
      'create_category': 'Kategorie erstellen',
      'monthly_limit_title': 'Monatslimit',
      'cancel': 'Abbrechen',
      'save': 'Speichern',
      'own_category': 'Eigene',
      'avg_per_day': 'Ø pro Tag',
      'top_category': 'Größte Ausgabe',
      'error_amount': 'Gib einen Betrag größer als null ein',
      'error_category_name': 'Gib einen Kategorienamen ein',
      'no_top_category': '—',
      'own_category_hint': 'eigene Kategorie',
      'cat_food': 'Essen', 'hint_food': 'z. B. Döner, Kaffee, Lebensmittel',
      'cat_transport': 'Transport', 'hint_transport': 'z. B. Taxi, Benzin, Bus',
      'cat_fun': 'Freizeit', 'hint_fun': 'z. B. Kino, Spiel, Konzert',
      'cat_clothes': 'Kleidung', 'hint_clothes': 'z. B. Sneaker, Jacke',
      'cat_home': 'Wohnen', 'hint_home': 'z. B. Miete, Nebenkosten',
      'cat_health': 'Gesundheit', 'hint_health': 'z. B. Apotheke, Arzt',
      'cat_subs': 'Abos', 'hint_subs': 'z. B. Musik, Streaming',
      'cat_beauty': 'Beauty', 'hint_beauty': 'z. B. Friseur, Kosmetik',
      'cat_study': 'Bildung', 'hint_study': 'z. B. Kurse, Bücher',
      'cat_gifts': 'Geschenke', 'hint_gifts': 'z. B. für Freunde, Familie',
      'cat_pets': 'Haustiere', 'hint_pets': 'z. B. Futter, Tierarzt',
      'cat_other': 'Sonstiges', 'hint_other': 'alles andere',
    },
    AppLanguage.ar: {
      'app_title': 'مصاريفي',
      'period_week': 'أسبوع',
      'period_month': 'شهر',
      'period_all': 'كل الوقت',
      'spent': 'تم إنفاقه',
      'limit_over': 'تم تجاوز الحد',
      'limit_left': 'المتبقي',
      'limit_of': 'من',
      'set_limit': 'تعيين الحد الشهري',
      'change_limit': 'تغيير الحد',
      'add_expense': 'إضافة مصروف',
      'history': 'السجل',
      'search_hint': 'ابحث حسب الفئة أو الملاحظة',
      'empty_history': 'لا يوجد شيء بعد — اختر فئة أعلاه لإضافة أول مصروف.',
      'add_button': 'إضافة',
      'date': 'التاريخ',
      'comment_optional': 'ملاحظة (اختياري)',
      'new_category': 'فئة جديدة',
      'category_name_hint': 'اسم الفئة',
      'icon_label': 'الأيقونة',
      'color_label': 'اللون',
      'create_category': 'إنشاء فئة',
      'monthly_limit_title': 'الحد الشهري',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'own_category': 'خاصة',
      'avg_per_day': 'المتوسط اليومي',
      'top_category': 'الأكثر إنفاقًا',
      'error_amount': 'أدخل مبلغًا أكبر من صفر',
      'error_category_name': 'أدخل اسم الفئة',
      'no_top_category': '—',
      'own_category_hint': 'فئة خاصة',
      'cat_food': 'طعام', 'hint_food': 'مثال: شاورما، قهوة، بقالة',
      'cat_transport': 'مواصلات', 'hint_transport': 'مثال: تاكسي، وقود، حافلة',
      'cat_fun': 'ترفيه', 'hint_fun': 'مثال: سينما، لعبة، حفلة',
      'cat_clothes': 'ملابس', 'hint_clothes': 'مثال: أحذية رياضية، جاكيت',
      'cat_home': 'سكن', 'hint_home': 'مثال: إيجار، فواتير',
      'cat_health': 'صحة', 'hint_health': 'مثال: صيدلية، طبيب',
      'cat_subs': 'اشتراكات', 'hint_subs': 'مثال: موسيقى، بث',
      'cat_beauty': 'جمال', 'hint_beauty': 'مثال: حلاقة، مستحضرات',
      'cat_study': 'دراسة', 'hint_study': 'مثال: دورات، كتب',
      'cat_gifts': 'هدايا', 'hint_gifts': 'مثال: لصديق، للعائلة',
      'cat_pets': 'حيوانات أليفة', 'hint_pets': 'مثال: طعام، بيطري',
      'cat_other': 'أخرى', 'hint_other': 'أي شيء آخر',
    },
    AppLanguage.zh: {
      'app_title': '我的支出',
      'period_week': '本周',
      'period_month': '本月',
      'period_all': '全部',
      'spent': '已花费',
      'limit_over': '已超出预算',
      'limit_left': '剩余',
      'limit_of': '/',
      'set_limit': '设置月度预算',
      'change_limit': '修改预算',
      'add_expense': '添加支出',
      'history': '历史记录',
      'search_hint': '按分类或备注搜索',
      'empty_history': '还没有记录 — 点击上方分类添加第一笔支出。',
      'add_button': '添加',
      'date': '日期',
      'comment_optional': '备注（可选）',
      'new_category': '新建分类',
      'category_name_hint': '分类名称',
      'icon_label': '图标',
      'color_label': '颜色',
      'create_category': '创建分类',
      'monthly_limit_title': '月度预算',
      'cancel': '取消',
      'save': '保存',
      'own_category': '自定义',
      'avg_per_day': '日均花费',
      'top_category': '最大支出',
      'error_amount': '请输入大于零的金额',
      'error_category_name': '请输入分类名称',
      'no_top_category': '—',
      'own_category_hint': '自定义分类',
      'cat_food': '餐饮', 'hint_food': '例如：沙威玛、咖啡、日用品',
      'cat_transport': '交通', 'hint_transport': '例如：打车、油费、公交',
      'cat_fun': '娱乐', 'hint_fun': '例如：电影、游戏、演唱会',
      'cat_clothes': '服饰', 'hint_clothes': '例如：运动鞋、外套',
      'cat_home': '住房', 'hint_home': '例如：房租、水电',
      'cat_health': '健康', 'hint_health': '例如：药店、看病',
      'cat_subs': '订阅', 'hint_subs': '例如：音乐、流媒体',
      'cat_beauty': '美容', 'hint_beauty': '例如：理发、化妆品',
      'cat_study': '学习', 'hint_study': '例如：课程、书籍',
      'cat_gifts': '礼物', 'hint_gifts': '例如：送朋友、送家人',
      'cat_pets': '宠物', 'hint_pets': '例如：食物、看兽医',
      'cat_other': '其他', 'hint_other': '其他任何东西',
    },
    AppLanguage.pt: {
      'app_title': 'Meus Gastos',
      'period_week': 'Semana',
      'period_month': 'Mês',
      'period_all': 'Sempre',
      'spent': 'GASTO',
      'limit_over': 'Limite excedido',
      'limit_left': 'Restam',
      'limit_of': 'de',
      'set_limit': 'Definir limite mensal',
      'change_limit': 'Alterar limite',
      'add_expense': 'ADICIONAR GASTO',
      'history': 'HISTÓRICO',
      'search_hint': 'Buscar por categoria ou nota',
      'empty_history': 'Ainda vazio — escolha uma categoria acima para adicionar seu primeiro gasto.',
      'add_button': 'Adicionar',
      'date': 'Data',
      'comment_optional': 'Nota (opcional)',
      'new_category': 'Nova categoria',
      'category_name_hint': 'nome da categoria',
      'icon_label': 'Ícone',
      'color_label': 'Cor',
      'create_category': 'Criar categoria',
      'monthly_limit_title': 'Limite mensal',
      'cancel': 'Cancelar',
      'save': 'Salvar',
      'own_category': 'Própria',
      'avg_per_day': 'Média diária',
      'top_category': 'Maior gasto',
      'error_amount': 'Digite um valor maior que zero',
      'error_category_name': 'Digite o nome da categoria',
      'no_top_category': '—',
      'own_category_hint': 'categoria própria',
      'cat_food': 'Comida', 'hint_food': 'ex: shawarma, café, mercado',
      'cat_transport': 'Transporte', 'hint_transport': 'ex: táxi, combustível, ônibus',
      'cat_fun': 'Lazer', 'hint_fun': 'ex: cinema, jogo, show',
      'cat_clothes': 'Roupas', 'hint_clothes': 'ex: tênis, jaqueta',
      'cat_home': 'Moradia', 'hint_home': 'ex: aluguel, contas',
      'cat_health': 'Saúde', 'hint_health': 'ex: farmácia, médico',
      'cat_subs': 'Assinaturas', 'hint_subs': 'ex: música, streaming',
      'cat_beauty': 'Beleza', 'hint_beauty': 'ex: cabeleireiro, cosméticos',
      'cat_study': 'Estudos', 'hint_study': 'ex: cursos, livros',
      'cat_gifts': 'Presentes', 'hint_gifts': 'ex: para um amigo, família',
      'cat_pets': 'Pets', 'hint_pets': 'ex: ração, veterinário',
      'cat_other': 'Outros', 'hint_other': 'qualquer outra coisa',
    },
  };

  static String t(AppLanguage lang, String key) {
    return _dict[lang]?[key] ?? _dict[AppLanguage.ru]![key] ?? key;
  }

  static String languageLabel(AppLanguage lang) {
    switch (lang) {
      case AppLanguage.ru: return 'Русский';
      case AppLanguage.en: return 'English';
      case AppLanguage.az: return 'Azərbaycan';
      case AppLanguage.tr: return 'Türkçe';
      case AppLanguage.es: return 'Español';
      case AppLanguage.fr: return 'Français';
      case AppLanguage.de: return 'Deutsch';
      case AppLanguage.ar: return 'العربية';
      case AppLanguage.zh: return '中文';
      case AppLanguage.pt: return 'Português';
    }
  }

  static String languageFlag(AppLanguage lang) {
    switch (lang) {
      case AppLanguage.ru: return '🇷🇺';
      case AppLanguage.en: return '🇬🇧';
      case AppLanguage.az: return '🇦🇿';
      case AppLanguage.tr: return '🇹🇷';
      case AppLanguage.es: return '🇪🇸';
      case AppLanguage.fr: return '🇫🇷';
      case AppLanguage.de: return '🇩🇪';
      case AppLanguage.ar: return '🇸🇦';
      case AppLanguage.zh: return '🇨🇳';
      case AppLanguage.pt: return '🇵🇹';
    }
  }

  /// Языки с письмом справа налево — потребуется для будущей поддержки RTL.
  static bool isRtl(AppLanguage lang) => lang == AppLanguage.ar;
}
